spring:
#H2
  h2:
    console:
      enabled: true
      path: /h2-console

#DATASOURCE
  datasource:
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:health

#JPA
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: create
    properties:
       hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect